version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/diaper_finder
    docker:
      - image: cimg/python:3.10.1-browsers
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: pwd
      - run: python --version
  test:
    working_directory: ~/diaper_finder
    docker:
      - image: cimg/python:3.10.1-browsers
    steps:
      - checkout
      - run: echo "this is the test job"
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run: pwd
      - run: ls -l
      - run: pip install -r ~/diaper_finder/requirements.txt
      - run: python diaper_finder.py

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
