version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1-browsers
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: python --version
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
  test:
    docker:
      - image: cimg/python:3.10.1-browsers
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
